# Generated by Django 3.2.9 on 2022-02-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_auto_20220222_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='insta_link',
            new_name='linkedin_link',
        ),
    ]
