# Generated by Django 3.2.9 on 2022-02-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_rename_insta_link_profile_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_link',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
